# Generated by Django 3.0 on 2020-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_auto_20200103_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
