# Generated by Django 3.0 on 2020-01-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_auto_20200110_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edithistory',
            name='post',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='codebase.Post'),
            preserve_default=False,
        ),
    ]
