# Generated by Django 3.0 on 2020-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0006_auto_20200104_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
