# Generated by Django 3.0 on 2020-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0007_auto_20200104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='post_pics'),
        ),
    ]
